apiVersion: v1
kind: Config
clusters:
  - name: tke
    cluster:
      certificate-authority: /etc/ca/mkcert/rootCA.pem
      server: https://tke_tkeplatformcontroller:9443
users:
  - name: admin
    user:
      token: token
current-context: tke
contexts:
  - context:
      cluster: tke
      user: admin
    name: tke